url: http://jsonapi.org
source: .
destination: ./public

# github pages we cannot customize
lsi: false
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
incremental: false
gist:
  noscript: false

# customize github pages
quiet: false
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  auto_id_prefix: auto-id-
  auto_id_stripping: true
  template: '' # cannot customize
  math_engine: mathjax # cannot customize
  syntax_highligher: rouge # cannot customize

plugins:
  - jekyll-redirect-from

exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss

port: 9876

collections:
  format:
    output: true
  errors:
    output: true
  profiles:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: format
    values:
      layout: page
      show_sidebar: true
      is_spec_page: true
  - scope:
      path: ""
      type: "profiles"
    values:
      layout: error
      is_spec_page: false
      show_sidebar: false
  - scope:
      path: ""
      type: "errors"
    values:
      layout: error
      is_spec_page: false
      show_sidebar: false
  - scope:
      path: "*/*/*/index.md"
      type: "profiles"
    values:
      layout: profile
      is_spec_page: false
      show_sidebar: true

latest_version: 1.0
excerpt_separator: ""
announcement: |
  **[JSON:API v1.1 RC1](/format/1.1/) has been published!** Please review and
  try out this upcoming version of the spec before its planned release date of
  January 31, 2019.

navigation:
- title: JSON API
  url: /
- title: Specification
  url: /format/
- title: Extensions
  url: /extensions/
- title: Recommendations
  url: /recommendations/
- title: Examples
  url: /examples/
- title: Implementations
  url: /implementations/
- title: FAQ
  url: /faq/
- title: About
  url: /about/

quicklinks:
- title: View the specification
  url: /format/
- title: Contribute on GitHub
  url: https://github.com/json-api/json-api

profile_categories:
  - Pagination
  - Resource Versioning
  # these are some other potential categories.
  # Uncomment them if you're adding a profile in one of these categories.
  # - Filtering
  # - Actions/Hypermedia
  # - Data Modeling
  # - Deep Querying
