url: http://jsonapi.org
safe: true
lsi: false
source: .
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
markdown: redcarpet
pygments: false
port: 9876

navigation:
- title: JSON:API
  url: /
- title: Format
  url: /format/
- title: Extensions
  url: /extensions/
- title: Recommendations
  url: /recommendations/
- title: Implementations
  url: /implementations/
- title: FAQ
  url: /faq/
- title: About
  url: /about/

quicklinks:
- title: Documentation
  url: /format/
- title: Github
  url: https://github.com/json-api/json-api